# Generated by Django 5.2.12 on 2026-04-07 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collateral', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collateralregistration',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral_records_as_debtor', to=settings.AUTH_USER_MODEL, verbose_name='Debtor'),
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='financier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral_records_as_financier', to=settings.AUTH_USER_MODEL, verbose_name='Financier'),
        ),
        migrations.AddIndex(
            model_name='collateralregistration',
            index=models.Index(fields=['agreement_start_date', 'agreement_end_date'], name='col_agreement_period_idx'),
        ),
        migrations.AddIndex(
            model_name='collateralregistration',
            index=models.Index(fields=['is_discharged', 'agreement_end_date'], name='col_discharge_status_idx'),
        ),
    ]
