# Generated by Django 5.2.12 on 2026-04-28 14:06

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('collateral', '0002_initial'),
        ('common', '0001_initial'),
        ('individuals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collateralregistration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.currency'),
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='financier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral_records_as_financier', to='clients.client', verbose_name='Financier'),
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='individual_debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collateral_records_as_individual_debtor', to='individuals.individual'),
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='collateralregistration',
            index=models.Index(fields=['agreement_start_date', 'agreement_end_date'], name='col_agreement_period_idx'),
        ),
        migrations.AddIndex(
            model_name='collateralregistration',
            index=models.Index(fields=['is_discharged', 'agreement_end_date'], name='col_discharge_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='collateralregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('asset_registration_number'), condition=models.Q(('is_discharged', False), models.Q(('asset_registration_number', ''), _negated=True)), name='col_uq_open_asset_reg_ci'),
        ),
        migrations.AddConstraint(
            model_name='collateralregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('chassis_number'), condition=models.Q(('is_discharged', False), models.Q(('chassis_number', ''), _negated=True)), name='col_uq_open_chassis_ci'),
        ),
        migrations.AddConstraint(
            model_name='collateralregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('serial_number'), condition=models.Q(('is_discharged', False), models.Q(('serial_number', ''), _negated=True)), name='col_uq_open_serial_ci'),
        ),
    ]
