# Generated by Django 5.2.12 on 2026-04-14 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0003_initial'),
        ('companies', '0002_initial'),
        ('individuals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateralregistration',
            name='debtor',
        ),
        migrations.RemoveField(
            model_name='collateralregistration',
            name='financier',
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='company_debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collateral_records_as_company_debtor', to='companies.companybranch'),
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='company_financier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collateral_records_as_company_financier', to='companies.companybranch'),
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='individual_debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collateral_records_as_individual_debtor', to='individuals.individual'),
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='individual_financier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collateral_records_as_individual_financier', to='individuals.individual'),
        ),
    ]
