# Generated by Django 5.2.12 on 2026-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateralregistration',
            name='condition',
            field=models.CharField(blank=True, max_length=20, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='collateralregistration',
            name='debtor_type',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Debtor Type'),
        ),
    ]
