# Generated by Django 5.2.12 on 2026-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0004_remove_collateralregistration_debtor_and_more'),
        ('common', '0002_initial'),
        ('companies', '0002_initial'),
        ('individuals', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collateralregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_discharged', False), models.Q(('asset_registration_number', ''), _negated=True)), fields=('asset_registration_number',), name='col_uq_open_asset_reg'),
        ),
        migrations.AddConstraint(
            model_name='collateralregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_discharged', False), models.Q(('chassis_number', ''), _negated=True)), fields=('chassis_number',), name='col_uq_open_chassis'),
        ),
        migrations.AddConstraint(
            model_name='collateralregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_discharged', False), models.Q(('serial_number', ''), _negated=True)), fields=('serial_number',), name='col_uq_open_serial'),
        ),
    ]
