# Generated by Django 5.2.12 on 2026-04-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('collateral', '0005_collateralregistration_col_uq_open_asset_reg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateralregistration',
            name='company_financier',
        ),
        migrations.RemoveField(
            model_name='collateralregistration',
            name='financier_type',
        ),
        migrations.RemoveField(
            model_name='collateralregistration',
            name='individual_financier',
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='financier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collateral_records_as_financier', to='clients.client', verbose_name='Financier'),
        ),
    ]
