# Generated by Django 5.2.12 on 2026-09-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0005_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateralregistration',
            name='data_source_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Data Source Name'),
        ),
        migrations.AddField(
            model_name='collateralregistration',
            name='data_source_position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Data Source Position'),
        ),
    ]
