# Generated by Django 5.2.12 on 2026-04-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('collateral', '0006_remove_collateralregistration_company_financier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateralregistration',
            name='financier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral_records_as_financier', to='clients.client', verbose_name='Financier'),
        ),
    ]
