# Generated by Django 5.2.12 on 2026-04-16 13:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('collateral', '0007_alter_collateralregistration_financier'),
        ('common', '0002_initial'),
        ('companies', '0002_initial'),
        ('individuals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collateralregistration',
            name='col_uq_open_asset_reg',
        ),
        migrations.RemoveConstraint(
            model_name='collateralregistration',
            name='col_uq_open_chassis',
        ),
        migrations.RemoveConstraint(
            model_name='collateralregistration',
            name='col_uq_open_serial',
        ),
        migrations.AddConstraint(
            model_name='collateralregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('asset_registration_number'), condition=models.Q(('is_discharged', False), models.Q(('asset_registration_number', ''), _negated=True)), name='col_uq_open_asset_reg_ci'),
        ),
        migrations.AddConstraint(
            model_name='collateralregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('chassis_number'), condition=models.Q(('is_discharged', False), models.Q(('chassis_number', ''), _negated=True)), name='col_uq_open_chassis_ci'),
        ),
        migrations.AddConstraint(
            model_name='collateralregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('serial_number'), condition=models.Q(('is_discharged', False), models.Q(('serial_number', ''), _negated=True)), name='col_uq_open_serial_ci'),
        ),
    ]
