# Generated by Django 5.2.12 on 2026-04-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0009_remove_collateralregistration_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateralregistration',
            name='position',
        ),
    ]
