# Generated by Django 5.2.12 on 2026-07-15 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEnquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('kind', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], db_index=True, max_length=20, verbose_name='Enquiry Kind')),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('branch_label', models.CharField(blank=True, max_length=255)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('search_field', models.CharField(blank=True, max_length=50)),
                ('result_found', models.BooleanField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_enquiries', to='clients.client', verbose_name='Client')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_enquiries_performed', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('requester', models.ForeignKey(blank=True, help_text='Client-side user for external enquiries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_enquiries_as_requester', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
            ],
            options={
                'verbose_name': 'Asset Enquiry Log',
                'verbose_name_plural': 'Asset Enquiry Logs',
                'ordering': ['-date_created'],
            },
        ),
    ]
