# Generated by Django 5.2.12 on 2026-04-07 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('individuals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='company',
            field=models.ForeignKey(help_text='The company this branch belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The company branch this contact person is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.companybranch'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='individual',
            field=models.ForeignKey(blank=True, help_text='The individual record if this contact person is also an Individual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_as_person', to='individuals.individual'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='The primary contact person for this company profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_as_primary_contact', to='companies.contactperson'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_name__isnull', True), _negated=True), fields=('registration_name',), name='unique_registration_name_company'),
        ),
        migrations.AddConstraint(
            model_name='companybranch',
            constraint=models.UniqueConstraint(fields=('company', 'branch_name'), name='unique_branch_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='contactperson',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_type', 'primary')), fields=('branch', 'contact_type'), name='unique_primary_branch_contact'),
        ),
    ]
