# Generated by Django 5.2.12 on 2026-04-28 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_management', '0002_initial'),
        ('common', '0001_initial'),
        ('individuals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetregistration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='individual_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='individuals.individual', verbose_name='Individual Owner'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assetregistration',
            index=models.Index(fields=['subscription_start_date', 'subscription_end_date'], name='ar_sub_period_idx'),
        ),
        migrations.AddIndex(
            model_name='assetregistration',
            index=models.Index(fields=['owner_type', 'individual_owner'], name='ar_owner_ind_idx'),
        ),
        migrations.AddIndex(
            model_name='assetregistration',
            index=models.Index(fields=['owner_type', 'company_owner'], name='ar_owner_comp_idx'),
        ),
    ]
