# Generated by Django 5.2.12 on 2026-04-07 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetregistration',
            name='owner',
            field=models.ForeignKey(help_text='Must already exist as a user in the system.', on_delete=django.db.models.deletion.PROTECT, related_name='registered_assets', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddIndex(
            model_name='assetregistration',
            index=models.Index(fields=['subscription_start_date', 'subscription_end_date'], name='ar_sub_period_idx'),
        ),
        migrations.AddIndex(
            model_name='assetregistration',
            index=models.Index(fields=['owner_type', 'owner'], name='ar_owner_type_idx'),
        ),
    ]
