# Generated by Django 5.2.12 on 2026-07-15 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_initial'),
        ('companies', '0002_initial'),
        ('individuals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetregistration',
            name='company_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_assets', to='companies.companybranch', verbose_name='Company Custodian'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='custodian_address',
            field=models.TextField(blank=True, verbose_name='Custodian Address'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='custodian_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Custodian Email'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='custodian_mobile',
            field=models.CharField(blank=True, max_length=30, verbose_name='Custodian Mobile'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='custodian_telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Custodian Telephone'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='custodian_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('company', 'Company')], max_length=20, verbose_name='Custodian Type'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='custody_type',
            field=models.CharField(blank=True, choices=[('rental', 'Rental'), ('escrow', 'Escrow'), ('consignment', 'Consignment'), ('trust', 'Trust'), ('arrangement', 'Arrangement'), ('employee', 'Employee')], db_index=True, help_text='When set, the asset is encumbered under custody (rule 1404.1.2).', max_length=20, verbose_name='Custody Type'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='guarantor_identification',
            field=models.CharField(blank=True, max_length=100, verbose_name='Guarantor ID'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Guarantor'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='individual_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_assets', to='individuals.individual', verbose_name='Individual Custodian'),
        ),
    ]
