# Generated by Django 5.2.12 on 2026-04-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_initial'),
        ('common', '0002_initial'),
        ('companies', '0002_initial'),
        ('individuals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assetregistration',
            name='ar_owner_type_idx',
        ),
        migrations.RemoveField(
            model_name='assetregistration',
            name='owner',
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='company_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.companybranch', verbose_name='Company Owner'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='individual_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='individuals.individual', verbose_name='Individual Owner'),
        ),
        migrations.AlterField(
            model_name='assetregistration',
            name='lodge_date',
            field=models.DateField(auto_now_add=True, verbose_name='Lodge Date'),
        ),
        migrations.AlterField(
            model_name='assetregistration',
            name='subscription_end_date',
            field=models.DateField(verbose_name='Subscription End Date'),
        ),
        migrations.AlterField(
            model_name='assetregistration',
            name='subscription_start_date',
            field=models.DateField(verbose_name='Subscription Start Date'),
        ),
        migrations.AddIndex(
            model_name='assetregistration',
            index=models.Index(fields=['owner_type', 'individual_owner'], name='ar_owner_ind_idx'),
        ),
        migrations.AddIndex(
            model_name='assetregistration',
            index=models.Index(fields=['owner_type', 'company_owner'], name='ar_owner_comp_idx'),
        ),
    ]
