# Generated by Django 5.2.12 on 2026-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0004_asset_enquiry_custody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetregistration',
            name='asset_type',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Asset Type'),
        ),
        migrations.AlterField(
            model_name='assetregistration',
            name='condition',
            field=models.CharField(blank=True, max_length=20, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='assetregistration',
            name='custodian_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Custodian Type'),
        ),
        migrations.AlterField(
            model_name='assetregistration',
            name='owner_type',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Owner Type'),
        ),
    ]
