# Generated by Django 5.2.12 on 2026-07-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0006_asset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetregistration',
            name='mv_registration_number',
            field=models.CharField(blank=True, db_index=True, help_text="Number plate. Required when asset_category is 'vehicles'; grey out otherwise.", max_length=50, verbose_name='MV Registration Number'),
        ),
    ]
