# Generated by Django 5.2.12 on 2026-09-16 06:53

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0009_land_stand_address_required_unique'),
        ('common', '0010_building_registry_and_close'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetregistration',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed At'),
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, the registration is archived and excluded from active lists.', verbose_name='Is Closed'),
        ),
        migrations.CreateModel(
            name='BuildingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('stand_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Stand Number')),
                ('building_type', models.CharField(choices=[('residential_house', 'Residential - House'), ('residential_cottage', 'Residential - Cottage'), ('residential_townhouse', 'Residential - Townhouse'), ('residential_flat', 'Residential - Flat'), ('residential_small_holding', 'Residential - Small Holding'), ('commercial_offices', 'Commercial - Offices'), ('commercial_retail', 'Commercial - Retail'), ('commercial_industrial', 'Commercial - Industrial'), ('commercial_warehouse', 'Commercial - Warehouse'), ('commercial_hospitality', 'Commercial - Hospitality'), ('institutional_education', 'Institutional - Education'), ('institutional_medical', 'Institutional - Medical'), ('agricultural_warehouse', 'Agricultural - Warehouse'), ('agricultural_greenhouse', 'Agricultural - Greenhouse')], max_length=50, verbose_name='Building Type')),
                ('description', models.TextField(blank=True, verbose_name='Property Details')),
                ('building_name', models.CharField(blank=True, max_length=255, verbose_name='Building/Complex Name')),
                ('total_number_of_units', models.PositiveIntegerField(default=0, verbose_name='Total Number of Units')),
                ('total_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Area (sq m)')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Built')),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('partially_occupied', 'Partially Occupied'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('sold', 'Sold')], max_length=30, verbose_name='Status')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Furnished')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Parking, security, and backup power options.', verbose_name='Features')),
                ('valuation_type', models.CharField(choices=[('purchase_price', 'Purchase Price'), ('estimated_value', 'Estimated Value'), ('professional_valuation', 'Professional Valuation')], max_length=30, verbose_name='Valuation Type')),
                ('title_status', models.CharField(choices=[('deeds', 'Deeds'), ('purchase_agreement', 'Purchase Agreement')], max_length=30, verbose_name='Title Status')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='asset_management.assetregistration', verbose_name='Asset')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='building_assets', to='common.city', verbose_name='City/Town')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='building_assets', to='common.suburb', verbose_name='Suburb/Area/Development')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Building Details',
                'verbose_name_plural': 'Building Details',
                'constraints': [models.UniqueConstraint(models.F('suburb'), django.db.models.functions.text.Lower('street_address'), name='ar_uq_building_suburb_address_ci')],
            },
        ),
    ]
