# Generated by Django 5.2.12 on 2026-09-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0010_building_registry_and_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='title_status',
            field=models.CharField(blank=True, choices=[('deeds', 'Deeds'), ('purchase_agreement', 'Purchase Agreement')], default='', max_length=30, verbose_name='Title Status'),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='valuation_type',
            field=models.CharField(blank=True, choices=[('purchase_price', 'Purchase Price'), ('estimated_value', 'Estimated Value'), ('professional_valuation', 'Professional Valuation')], default='', max_length=30, verbose_name='Valuation Type'),
        ),
    ]
