# Generated by Django 5.2.12 on 2026-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PartyType', 'Party Type'), ('BaseAssetType', 'Base Asset Type'), ('AssetCondition', 'Asset Condition')], db_index=True, max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('is_system', models.BooleanField(default=False, help_text='System rows are seeded from built-in enums and cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lookup Option',
                'verbose_name_plural': 'Lookup Options',
                'ordering': ['category', 'sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('category', 'value'), name='uniq_lookup_option_category_value')],
            },
        ),
    ]
