# Generated by Django 5.2.12 on 2026-09-16 06:53

from django.db import migrations, models


def reseed_building_lookups(apps, schema_editor):
    from apps.common.utils.seed_lookups import seed_system_lookup_options
    from apps.common.utils.lookups import invalidate_common_choices_cache

    seed_system_lookup_options(LookupOption=apps.get_model("common", "LookupOption"))
    invalidate_common_choices_cache()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_reseed_land_lookups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupoption',
            name='category',
            field=models.CharField(choices=[('PartyType', 'Party Type'), ('BaseAssetType', 'Base Asset Type'), ('AssetCondition', 'Asset Condition'), ('CollateralAssetCategory', 'Collateral Asset Category'), ('Industry', 'Industry'), ('ValuationType', 'Valuation Type'), ('TitleStatus', 'Title Status'), ('SaleTerms', 'Sale Terms'), ('BuildingType', 'Building Type'), ('BuildingStatus', 'Building Status')], db_index=True, max_length=50),
        ),
        migrations.RunPython(reseed_building_lookups, migrations.RunPython.noop),
    ]
