# Generated by Django 5.2.12 on 2026-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text="Unique name for the role (e.g., 'Client Admin', 'Client User').", max_length=100, unique=True),
        ),
    ]
