# Generated by Django 5.2.12 on 2026-04-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, help_text="The user's job title or position within their organization.", max_length=100, null=True),
        ),
    ]
