# Generated by Django 6.0.1 on 2026-04-06 08:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assetsafe", "0001_remove_old_models"),
    ]

    operations = [
        migrations.CreateModel(
            name='HirePurchaseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_date', models.DateField(default=django.utils.timezone.now, help_text='Date the record is lodged; defaults to today.', verbose_name='Data Date')),
                ('purchaser_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], db_index=True, max_length=20, verbose_name='Purchaser Type')),
                ('agreement_number', models.CharField(db_index=True, help_text="The financier's own agreement reference number.", max_length=100, verbose_name='Agreement Number')),
                ('asset_type', models.CharField(choices=[('computers', 'Computers'), ('machinery', 'Machinery'), ('equipment', 'Equipment'), ('vehicles', 'Vehicles'), ('land', 'Land'), ('building', 'Building'), ('furniture', 'Furniture'), ('shares', 'Shares')], db_index=True, max_length=30, verbose_name='Asset Type')),
                ('make', models.CharField(blank=True, max_length=100, verbose_name='Make')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('year_of_make', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of Make')),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('second_hand', 'Second Hand'), ('reconditioned', 'Reconditioned'), ('non_functioning', 'Non Functioning')], max_length=20, verbose_name='Condition')),
                ('mv_registration_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='MV Registration Number')),
                ('chassis_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Chassis Number')),
                ('engine_number', models.CharField(blank=True, max_length=100, verbose_name='Engine Number')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Serial Number')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZWL', 'Zimbabwean Dollar'), ('ZAR', 'South African Rand'), ('GBP', 'British Pound'), ('EUR', 'Euro')], max_length=10, verbose_name='Currency')),
                ('purchase_amount', models.DecimalField(decimal_places=2, help_text='Total contractual amount to be paid over the HP period.', max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Purchase Amount')),
                ('instalment_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Instalment Amount')),
                ('instalment_day', models.PositiveSmallIntegerField(help_text='Day-of-month (dd) when each instalment falls due.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Instalment Day')),
                ('total_paid_to_date', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Paid to Date')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Stored derived value: purchase_amount - total_paid_to_date.', max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance')),
                ('agreement_start_date', models.DateField(db_index=True, verbose_name='Agreement Start Date')),
                ('agreement_end_date', models.DateField(db_index=True, verbose_name='Agreement End Date')),
                ('lodge_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Lodge Date')),
                ('closure_confirmed', models.BooleanField(db_index=True, default=False, help_text="Financier must actively confirm when an agreement closes. Until confirmed, an ended agreement is counted as 'Pending Closure Confirmation'.", verbose_name='Closure Confirmed')),
                ('closure_confirmed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Closure Confirmed At')),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_financier', to=settings.AUTH_USER_MODEL, verbose_name='Financier')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_purchaser', to=settings.AUTH_USER_MODEL, verbose_name='Purchaser')),
            ],
            options={
                'verbose_name': 'Hire Purchase Registration',
                'verbose_name_plural': 'Hire Purchase Registrations',
                'ordering': ['-lodge_date'],
                'indexes': [models.Index(fields=['agreement_start_date', 'agreement_end_date'], name='hp_agreement_period_idx'), models.Index(fields=['closure_confirmed', 'agreement_end_date'], name='hp_closure_status_idx'), models.Index(fields=['financier', 'closure_confirmed'], name='hp_financier_closure_idx')],
            },
        ),
    ]
