# Generated by Django 5.2.12 on 2026-04-07 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hire_purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='financier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_financier', to=settings.AUTH_USER_MODEL, verbose_name='Financier'),
        ),
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_purchaser', to=settings.AUTH_USER_MODEL, verbose_name='Purchaser'),
        ),
        migrations.AddIndex(
            model_name='hirepurchaseregistration',
            index=models.Index(fields=['agreement_start_date', 'agreement_end_date'], name='hp_agreement_period_idx'),
        ),
        migrations.AddIndex(
            model_name='hirepurchaseregistration',
            index=models.Index(fields=['closure_confirmed', 'agreement_end_date'], name='hp_closure_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hirepurchaseregistration',
            index=models.Index(fields=['financier', 'closure_confirmed'], name='hp_financier_closure_idx'),
        ),
    ]
