# Generated by Django 5.2.12 on 2026-04-28 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('common', '0001_initial'),
        ('companies', '0002_initial'),
        ('hire_purchase', '0001_initial'),
        ('individuals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.currency'),
        ),
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='financier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_financier', to='clients.client', verbose_name='Financier'),
        ),
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='purchaser_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_purchaser', to='companies.companybranch', verbose_name='Purchaser (Company Branch)'),
        ),
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='purchaser_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_purchaser', to='individuals.individual', verbose_name='Purchaser (Individual)'),
        ),
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hirepurchaseregistration',
            index=models.Index(fields=['agreement_start_date', 'agreement_end_date'], name='hp_agreement_period_idx'),
        ),
        migrations.AddIndex(
            model_name='hirepurchaseregistration',
            index=models.Index(fields=['closure_confirmed', 'agreement_end_date'], name='hp_closure_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hirepurchaseregistration',
            index=models.Index(fields=['financier', 'closure_confirmed'], name='hp_financier_closure_idx'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchaser_type', 'individual'), ('purchaser_company__isnull', True), ('purchaser_individual__isnull', False)), models.Q(('purchaser_type', 'company'), ('purchaser_company__isnull', False), ('purchaser_individual__isnull', True)), _connector='OR'), name='hp_exclusive_purchaser', violation_error_message='Purchaser type must match the provided purchaser (Individual or Company Branch), and only one must be provided.'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('mv_registration_number', ''), _negated=True), ('purchaser_individual__isnull', False)), fields=('financier', 'purchaser_individual', 'make', 'mv_registration_number'), name='hp_uniq_mv_reg_ind'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('mv_registration_number', ''), _negated=True), ('purchaser_company__isnull', False)), fields=('financier', 'purchaser_company', 'make', 'mv_registration_number'), name='hp_uniq_mv_reg_comp'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('serial_number', ''), _negated=True), ('purchaser_individual__isnull', False)), fields=('financier', 'purchaser_individual', 'make', 'serial_number'), name='hp_uniq_serial_ind'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('serial_number', ''), _negated=True), ('purchaser_company__isnull', False)), fields=('financier', 'purchaser_company', 'make', 'serial_number'), name='hp_uniq_serial_comp'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('mv_registration_number', ''), ('serial_number', ''), ('purchaser_individual__isnull', False)), fields=('financier', 'purchaser_individual', 'make'), name='hp_uniq_no_id_ind'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('mv_registration_number', ''), ('serial_number', ''), ('purchaser_company__isnull', False)), fields=('financier', 'purchaser_company', 'make'), name='hp_uniq_no_id_comp'),
        ),
    ]
