# Generated by Django 6.0.1 on 2026-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_purchase', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirepurchaseregistration',
            name='agreement_number',
            field=models.CharField(db_index=True, help_text="The financier's own agreement reference number.", max_length=100, unique=True, verbose_name='Agreement Number'),
        ),
    ]
