# Generated by Django 5.2.12 on 2026-04-18 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('common', '0002_initial'),
        ('hire_purchase', '0003_alter_hirepurchaseregistration_agreement_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirepurchaseregistration',
            name='financier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_financier', to='clients.client', verbose_name='Financier'),
        ),
        migrations.AlterField(
            model_name='hirepurchaseregistration',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_purchaser', to='clients.client', verbose_name='Purchaser'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('mv_registration_number', ''), _negated=True), fields=('financier', 'purchaser', 'make', 'mv_registration_number'), name='hp_uniq_mv_reg', violation_error_message='A Hire Purchase agreement for this make and MV registration number between this financier and purchaser already exists.'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('financier', 'purchaser', 'make', 'serial_number'), name='hp_uniq_serial', violation_error_message='A Hire Purchase agreement for this make and serial number between this financier and purchaser already exists.'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('mv_registration_number', ''), ('serial_number', '')), fields=('financier', 'purchaser', 'make'), name='hp_uniq_no_id', violation_error_message='A Hire Purchase agreement for this make between this financier and purchaser without registration or serial numbers already exists.'),
        ),
    ]
