# Generated by Django 5.2.12 on 2026-04-18 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('common', '0002_initial'),
        ('companies', '0002_initial'),
        ('hire_purchase', '0004_alter_hirepurchaseregistration_financier_and_more'),
        ('individuals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hirepurchaseregistration',
            name='hp_uniq_mv_reg',
        ),
        migrations.RemoveConstraint(
            model_name='hirepurchaseregistration',
            name='hp_uniq_serial',
        ),
        migrations.RemoveConstraint(
            model_name='hirepurchaseregistration',
            name='hp_uniq_no_id',
        ),
        migrations.RemoveField(
            model_name='hirepurchaseregistration',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='hirepurchaseregistration',
            name='purchaser_type',
        ),
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='purchaser_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_purchaser', to='companies.companybranch', verbose_name='Purchaser (Company Branch)'),
        ),
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='purchaser_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hp_records_as_purchaser', to='individuals.individual', verbose_name='Purchaser (Individual)'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchaser_company__isnull', True), ('purchaser_individual__isnull', False)), models.Q(('purchaser_company__isnull', False), ('purchaser_individual__isnull', True)), _connector='OR'), name='hp_exclusive_purchaser', violation_error_message='Either purchaser_individual or purchaser_company must be provided, but not both.'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('mv_registration_number', ''), _negated=True), ('purchaser_individual__isnull', False)), fields=('financier', 'purchaser_individual', 'make', 'mv_registration_number'), name='hp_uniq_mv_reg_ind'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('mv_registration_number', ''), _negated=True), ('purchaser_company__isnull', False)), fields=('financier', 'purchaser_company', 'make', 'mv_registration_number'), name='hp_uniq_mv_reg_comp'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('serial_number', ''), _negated=True), ('purchaser_individual__isnull', False)), fields=('financier', 'purchaser_individual', 'make', 'serial_number'), name='hp_uniq_serial_ind'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('serial_number', ''), _negated=True), ('purchaser_company__isnull', False)), fields=('financier', 'purchaser_company', 'make', 'serial_number'), name='hp_uniq_serial_comp'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('mv_registration_number', ''), ('serial_number', ''), ('purchaser_individual__isnull', False)), fields=('financier', 'purchaser_individual', 'make'), name='hp_uniq_no_id_ind'),
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('mv_registration_number', ''), ('serial_number', ''), ('purchaser_company__isnull', False)), fields=('financier', 'purchaser_company', 'make'), name='hp_uniq_no_id_comp'),
        ),
    ]
