# Generated by Django 5.2.12 on 2026-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('common', '0002_initial'),
        ('companies', '0002_initial'),
        ('hire_purchase', '0005_remove_hirepurchaseregistration_hp_uniq_mv_reg_and_more'),
        ('individuals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hirepurchaseregistration',
            name='hp_exclusive_purchaser',
        ),
        migrations.AddField(
            model_name='hirepurchaseregistration',
            name='purchaser_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], db_index=True, default='individual', max_length=20, verbose_name='Purchaser Type'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='hirepurchaseregistration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchaser_type', 'individual'), ('purchaser_company__isnull', True), ('purchaser_individual__isnull', False)), models.Q(('purchaser_type', 'company'), ('purchaser_company__isnull', False), ('purchaser_individual__isnull', True)), _connector='OR'), name='hp_exclusive_purchaser', violation_error_message='Purchaser type must match the provided purchaser (Individual or Company Branch), and only one must be provided.'),
        ),
    ]
