# Generated by Django 5.2.12 on 2026-04-01 09:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration_number",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Internally generated sequential identifier, e.g. AR000001.",
                        max_length=20,
                        unique=True,
                        verbose_name="Registration Number",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("company", "Company")],
                        db_index=True,
                        max_length=20,
                        verbose_name="Owner Type",
                    ),
                ),
                (
                    "owner_asset_number",
                    models.CharField(
                        blank=True,
                        help_text="Company's own internal code for this asset, if applicable.",
                        max_length=100,
                        verbose_name="Owner Asset Number",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("computers", "Computers"),
                            ("machinery", "Machinery"),
                            ("equipment", "Equipment"),
                            ("vehicles", "Vehicles"),
                            ("land", "Land"),
                            ("building", "Building"),
                            ("furniture", "Furniture"),
                            ("shares", "Shares"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Asset Type",
                    ),
                ),
                (
                    "make",
                    models.CharField(blank=True, max_length=100, verbose_name="Make"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="Model"),
                ),
                (
                    "year_of_make",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Year of Make"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("second_hand", "Second Hand"),
                            ("reconditioned", "Reconditioned"),
                            ("non_functioning", "Non Functioning"),
                        ],
                        max_length=20,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "mv_registration_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Number plate. Required when asset_type is 'vehicles'; grey out otherwise.",
                        max_length=50,
                        verbose_name="MV Registration Number",
                    ),
                ),
                (
                    "chassis_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Chassis Number",
                    ),
                ),
                (
                    "engine_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Engine Number"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="For non-vehicle assets that carry a serial number.",
                        max_length=100,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("ZWL", "Zimbabwean Dollar"),
                            ("ZAR", "South African Rand"),
                            ("GBP", "British Pound"),
                            ("EUR", "Euro"),
                        ],
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Estimated Value",
                    ),
                ),
                (
                    "location_address",
                    models.TextField(
                        help_text="Physical address where the asset is normally kept. For moveable assets, use the owner's address.",
                        verbose_name="Location Address",
                    ),
                ),
                (
                    "lodge_date",
                    models.DateField(
                        auto_now_add=True, db_index=True, verbose_name="Lodge Date"
                    ),
                ),
                (
                    "subscription_start_date",
                    models.DateField(
                        db_index=True, verbose_name="Subscription Start Date"
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateField(
                        db_index=True, verbose_name="Subscription End Date"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Must already exist as a user in the system.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Registration",
                "verbose_name_plural": "Asset Registrations",
                "ordering": ["-lodge_date"],
                "indexes": [
                    models.Index(
                        fields=["subscription_start_date", "subscription_end_date"],
                        name="ar_sub_period_idx",
                    ),
                    models.Index(
                        fields=["owner_type", "owner"], name="ar_owner_type_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CollateralRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financier_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("company", "Company")],
                        db_index=True,
                        max_length=20,
                        verbose_name="Financier Type",
                    ),
                ),
                (
                    "data_source_name",
                    models.CharField(
                        help_text="Full name of the financier representative supplying this record.",
                        max_length=200,
                        verbose_name="Data Source Name",
                    ),
                ),
                (
                    "data_date",
                    models.DateField(
                        help_text="Date on which the financier wants the record lodged.",
                        verbose_name="Data Date",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Job title of the data-source representative within the financier organisation.",
                        max_length=100,
                        verbose_name="Position",
                    ),
                ),
                (
                    "debtor_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("company", "Company")],
                        db_index=True,
                        max_length=20,
                        verbose_name="Debtor Type",
                    ),
                ),
                (
                    "agreement_number",
                    models.CharField(
                        db_index=True,
                        help_text="The loan reference number issued by the lender.",
                        max_length=100,
                        verbose_name="Agreement Number",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("computers", "Computers"),
                            ("machinery", "Machinery"),
                            ("equipment", "Equipment"),
                            ("vehicles", "Vehicles"),
                            ("land", "Land"),
                            ("building", "Building"),
                            ("furniture", "Furniture"),
                            ("shares", "Shares"),
                            ("inventory", "Inventory"),
                            ("accounts_receivable", "Accounts Receivable"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Asset Type",
                    ),
                ),
                (
                    "make",
                    models.CharField(blank=True, max_length=100, verbose_name="Make"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="Model"),
                ),
                (
                    "year_of_make",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Year of Make"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("second_hand", "Second Hand"),
                            ("reconditioned", "Reconditioned"),
                            ("non_functioning", "Non Functioning"),
                        ],
                        max_length=20,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "asset_registration_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Vehicle registration plate, if applicable.",
                        max_length=50,
                        verbose_name="Asset Registration Number",
                    ),
                ),
                (
                    "chassis_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Chassis Number",
                    ),
                ),
                (
                    "engine_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Engine Number"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("ZWL", "Zimbabwean Dollar"),
                            ("ZAR", "South African Rand"),
                            ("GBP", "British Pound"),
                            ("EUR", "Euro"),
                        ],
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "total_debt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Debt",
                    ),
                ),
                (
                    "instalment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Instalment Amount",
                    ),
                ),
                (
                    "instalment_day",
                    models.PositiveSmallIntegerField(
                        help_text="Day-of-month (dd) when each instalment falls due.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Instalment Day",
                    ),
                ),
                (
                    "total_paid_to_date",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Paid to Date",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stored derived value: total_debt total_paid_to_date.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Balance",
                    ),
                ),
                (
                    "agreement_start_date",
                    models.DateField(
                        db_index=True, verbose_name="Agreement Start Date"
                    ),
                ),
                (
                    "agreement_end_date",
                    models.DateField(db_index=True, verbose_name="Agreement End Date"),
                ),
                (
                    "lodge_date",
                    models.DateField(
                        auto_now_add=True, db_index=True, verbose_name="Lodge Date"
                    ),
                ),
                (
                    "is_discharged",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Set to True when the financier officially releases the collateral encumbrance.",
                        verbose_name="Is Discharged",
                    ),
                ),
                (
                    "discharge_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Discharge Confirmed At",
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collateral_records_as_debtor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Debtor",
                    ),
                ),
                (
                    "financier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collateral_records_as_financier",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Financier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collateral Registration",
                "verbose_name_plural": "Collateral Registrations",
                "ordering": ["-lodge_date"],
                "indexes": [
                    models.Index(
                        fields=["agreement_start_date", "agreement_end_date"],
                        name="col_agreement_period_idx",
                    ),
                    models.Index(
                        fields=["is_discharged", "agreement_end_date"],
                        name="col_discharge_status_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HirePurchaseRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date the record is lodged; defaults to today.",
                        verbose_name="Data Date",
                    ),
                ),
                (
                    "purchaser_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("company", "Company")],
                        db_index=True,
                        max_length=20,
                        verbose_name="Purchaser Type",
                    ),
                ),
                (
                    "agreement_number",
                    models.CharField(
                        db_index=True,
                        help_text="The financier's own agreement reference number.",
                        max_length=100,
                        verbose_name="Agreement Number",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("computers", "Computers"),
                            ("machinery", "Machinery"),
                            ("equipment", "Equipment"),
                            ("vehicles", "Vehicles"),
                            ("land", "Land"),
                            ("building", "Building"),
                            ("furniture", "Furniture"),
                            ("shares", "Shares"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Asset Type",
                    ),
                ),
                (
                    "make",
                    models.CharField(blank=True, max_length=100, verbose_name="Make"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="Model"),
                ),
                (
                    "year_of_make",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Year of Make"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("second_hand", "Second Hand"),
                            ("reconditioned", "Reconditioned"),
                            ("non_functioning", "Non Functioning"),
                        ],
                        max_length=20,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "mv_registration_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="MV Registration Number",
                    ),
                ),
                (
                    "chassis_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Chassis Number",
                    ),
                ),
                (
                    "engine_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Engine Number"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("ZWL", "Zimbabwean Dollar"),
                            ("ZAR", "South African Rand"),
                            ("GBP", "British Pound"),
                            ("EUR", "Euro"),
                        ],
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total contractual amount to be paid over the HP period.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Purchase Amount",
                    ),
                ),
                (
                    "instalment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Instalment Amount",
                    ),
                ),
                (
                    "instalment_day",
                    models.PositiveSmallIntegerField(
                        help_text="Day-of-month (dd) when each instalment falls due.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Instalment Day",
                    ),
                ),
                (
                    "total_paid_to_date",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Paid to Date",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stored derived value: purchase_amount - total_paid_to_date.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Balance",
                    ),
                ),
                (
                    "agreement_start_date",
                    models.DateField(
                        db_index=True, verbose_name="Agreement Start Date"
                    ),
                ),
                (
                    "agreement_end_date",
                    models.DateField(db_index=True, verbose_name="Agreement End Date"),
                ),
                (
                    "lodge_date",
                    models.DateField(
                        auto_now_add=True, db_index=True, verbose_name="Lodge Date"
                    ),
                ),
                (
                    "closure_confirmed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Financier must actively confirm when an agreement closes. Until confirmed, an ended agreement is counted as 'Pending Closure Confirmation'.",
                        verbose_name="Closure Confirmed",
                    ),
                ),
                (
                    "closure_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Closure Confirmed At",
                    ),
                ),
                (
                    "financier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hp_records_as_financier",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Financier",
                    ),
                ),
                (
                    "purchaser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hp_records_as_purchaser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Purchaser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hire Purchase Registration",
                "verbose_name_plural": "Hire Purchase Registrations",
                "ordering": ["-lodge_date"],
                "indexes": [
                    models.Index(
                        fields=["agreement_start_date", "agreement_end_date"],
                        name="hp_agreement_period_idx",
                    ),
                    models.Index(
                        fields=["closure_confirmed", "agreement_end_date"],
                        name="hp_closure_status_idx",
                    ),
                    models.Index(
                        fields=["financier", "closure_confirmed"],
                        name="hp_financier_closure_idx",
                    ),
                ],
            },
        ),
    ]
