# Generated by Django 6.0.1 on 2026-04-06 08:23

from django.db import migrations


def drop_old_tables(apps, schema_editor):
    """Drop the old model tables from assetsafe app."""
    schema_editor.execute("DROP TABLE IF EXISTS assetsafe_hirepurchaseregistration CASCADE")
    schema_editor.execute("DROP TABLE IF EXISTS assetsafe_collateralregistration CASCADE")
    schema_editor.execute("DROP TABLE IF EXISTS assetsafe_assetregistration CASCADE")


def no_op(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(drop_old_tables, no_op),
    ]
